# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'CryptoTracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CryptoTracker
pod 'Moya', '~> 15.0'
pod 'Kingfisher', '~> 7.0'

  target 'CryptoTrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CryptoTrackerUITests' do
    # Pods for testing
  end

end
